### PR TITLE
Update role for ubuntu-16.04 and remove nginx pin

### PR DESCRIPTION
**Pull request by mvdbeek**
for my nginx ppa. I kept the galxyproject pin for now, but maybe we should just point at my ppa for this as well.

### CODE REVIEW

**Comment by afgane** [comment]
So why is the pin for your PPA no longer necessary?

**Comment by mvdbeek** [comment]
Travis is building and uploading the package every night from my starforge fork,
you can see this for the last 2 months here: https://travis-ci.org/mvdbeek/starforge/builds
If upstream updates their build we'll be behind for a maximum of 24 hours.

**Comment by afgane** [comment]
I see. I feel this should be documented though because if a build yields a working instance one day and then a non-working one the next day, this cause may be difficult to track down.

**Comment by mvdbeek** [comment]
Well, where do you want to document it? A line on the task where the ppa is added?
That won't necessarily help though if you are facing a non-working build, since that is not where things will fail (and hence where you would suspect something to be wrong in the first place).

**Comment by afgane** [comment]
I agree. On the surface, the build will complete OK but some Galaxy functionality will not work - that's why this will be a tricky issue to resolve. 

An inline comment where the nginx PPA will be nice but what do you think about perhaps also adding a couple of sentences in the README about this? Perhaps adding a _Troubleshooting_ section to the README and adding this there?

**Comment by mvdbeek** [comment]
I can do this, but https://galaxyproject.org/admin/config/nginxProxy/ is not migrated yet apparently ... i think a lot could be copy-pasted from there.

**Comment by afgane** [comment]
This is be the new URL for that page: https://galaxyproject.org/admin/config/nginx-proxy/ but rather than copying and pasting a bunch of content, perhaps including the link will be enough...

**Comment by mvdbeek** [comment]
Alright, I've added a note and added you as a collaborator on my fork, which should let you trigger new builds in travis. The complementary PR to starforge is https://github.com/galaxyproject/starforge/pull/125 ... which would need to see some activity from Nate if we want to move this to the galaxyproject PPA

**Comment by afgane** [comment]
Thanks for adding that.
What about the failing test - I'm not sure why it's being skipped for the first two iterations and not the last one since they're all running dockerized?

**Comment by mvdbeek** [comment]
No idea for now, I'm guessing the ansible inventar setup doesn't work properly for some reason. I'll have a look locally.

**Comment by afgane** [comment]
I'm guessing this is obsolete at this point?

**Comment by mvdbeek** [comment]
Yup!

**Pull request closed without merging**
